### PR TITLE
Improve WatchAnalytics Styling

### LINKED ISSUE #21: README doesn't have up to date info
Description is wrong, and doesn't have install instructions.

### LINKED ISSUE #46: Make color schemes match between Page Scores and Pending Reviews
The legend on Pending Reviews stating how the color coding works does not jive with Page Scores. It should, I think.

Pending reviews legend:
image

Page scores shows the following colors for reviews:

2 Reviews: 
image

3 Reviews: 
image

4 Reviews: 
image

5 Reviews:
image

### LINKED ISSUE #55: cssColorClasses should be configurable
Right now this is hard-coded into the class:

``` php
    public function __construct ( Title $title ) {

        $this->mTitle = $title;
        $this->cssColorClasses = array(
            'excellent',
            // 'good',
            'okay',
            // 'warning',
            'danger',
        );
    }
```

Instead the config object should be read.  Defaults should be kept in extension.json.

### PR DESCRIPTION
**Pull request by krisfield**
- Makes CSS configurable colors/thresholds configurable
- Uses Mediawiki [utility colors](https://design.wikimedia.org/style-guide/visual-style_colors.html)
- Cleans up README page since content is on MediaWiki.org

**Issues**
1. Closes #55 
2. Closes #46 
3. Closes #21

### CODE REVIEW

**Comment by krisfield** [comment]
This is ready to be merged once you've completed a final review

**Comment by jamesmontalvo3** [comment]
I tried to go plaid by adding the following to settings:

```php
$egWatchAnalyticsWatchQualityColors = [
	"21" => "plaid",
	"5" => "excellent",
	"1.5" => "okay"
];
```

Without that change one page's scores look like:

image

With that change above they look the same. If I make this change:

```php
$egWatchAnalyticsWatchQualityColors = [
	21 => "plaid",
	5 => "excellent",
	1.5 => "okay"
];
```

then I get:

image

Changing `21 => "plaid"` to `10 => "plaid"` still no change.

Show me plaid!

**Comment by jamesmontalvo3** [comment]
If I modify `extension.json` to say `"10" : "plaid"` instead of `"50" : "plaid"` then I get glorious plaid:

image

**Comment by krisfield** [comment]
> I made this change to `extension.json` to make it respect my changes to `LocalSettings.php`:
> 
> ```diff
>                 "WatchAnalyticsWatchQualityColors": {
>                         "50" : "plaid",
>                         "5" : "excellent",
> -                       "1.5" : "okay"
> +                       "1.5" : "okay",
> +                       "_merge_strategy": "array_plus"
>                 },
>                 "WatchAnalyticsReviewStatusColors": {
>                         "5" : "excellent",
> ```
> 
> Ref: https://www.mediawiki.org/wiki/Manual:Extension.json/Schema#Merge_strategies
> 
> Basically with extension registration (i.e. `extension.json`) you have to tell it how you want array globals to be handled. Do you want them to be overwritten, merged, etc. I'm not sure `array_plus` is the perfect solution, but it may be the best available option. I don't recall why the arrays are written in the form `50 => "plaid"` versus `"plaid" => 50`, but that may be better.

Thanks for the catch. I added the "array_plus" handling. As far as having numbered keys vs strings I think the current layout makes the most sense. Having the strings as keys seems weird to me.

**Comment by jamesmontalvo3** [comment]
Have you tested different configurations in `LocalSettings.php` to verify things are working as expected?

**Comment by krisfield** [comment]
Yes, that's how i tested the change

**Pull request merged**
