### PR TITLE
Adds diff to 'unreview' banner and Special:PendingReviews

### PR DESCRIPTION
**Pull request by krisfield**
This makes it clear to a user that changes have been made even if they navigate to the page directly (not from Special:PendingReviews)
image

### CODE REVIEW

**Comment by jamesmontalvo3** [comment]
Remove yellow highlight on hover over "mark reviewed" button

image

**Comment by jamesmontalvo3** [comment]
When unexpectedly navigating to a page that has been modified WatchAnalytics has always presented a banner that said "this page has been reviewed" and gave you a "defer review" button to un-review it.

Changes @krisfield has made:
1. Added the diff of the change to the banner
2. Make it so the "defer review" button doesn't navigate you away from the page, and simply removes the banner.

An additional change that should be added: a "close" or "accept review" button, e.g.:

image

This would close the banner, but not add the review back to your list. At the point that you're seeing this you've already implicitly reviewed the page, so "close" seems all that is really necessary. However, it may be better to say "accept" or "accept review" so people understand better. Also that may lead in better to when we have the ability to do _____ explicit reviews.

**Comment by jamesmontalvo3** [comment]
From our other discussions, it is clear that it is not easy to simply generate the standard diff headers (see below):

image

However, it shouldn't be too hard to simulate some of the information. Dates, authors, and comments seems like the important stuff. Hopefully we can make it easier to grab the standard header after MW 1.33.

**Comment by jamesmontalvo3** [comment]
Mousing over the first item in "Pages needing your approval" highlights the first item (obviously), but it also highlights the first item in the pending reviews list. Ditto for item 2, 3, 4, ...

**Comment by krisfield** [comment]
> When unexpectedly navigating to a page that has been modified WatchAnalytics has always presented a banner that said "this page has been reviewed" and gave you a "defer review" button to un-review it.
> 
> Changes @krisfield has made:
> 
>     1. Added the diff of the change to the banner
> 
>     2. Make it so the "defer review" button doesn't navigate you away from the page, and simply removes the banner.
> 
> 
> An additional change that should be added: a "close" or "accept review" button, e.g.:
> 
> image
> 
> This would close the banner, but not add the review back to your list. At the point that you're seeing this you've already implicitly reviewed the page, so "close" seems all that is really necessary. However, it may be better to say "accept" or "accept review" so people understand better. Also that may lead in better to when we have the ability to do _____ explicit reviews.

Button added. I think "Close banner" is less confusing to users since they don't need to click this button to 'accept changes'

image

**Comment by krisfield** [comment]
@jamesmontalvo3 let me know what you think and lets merge this week

**Comment by krisfield** [comment]
Verified that these changes work as expected

**Pull request merged**
