### PR TITLE
Update PendingReview.php

### PR DESCRIPTION
**Pull request by revansx**
required to process certain pages based on MW use of new "actor" table

### CODE REVIEW

**Comment by jamesmontalvo3** [comment]
I haven't seen this cause an issue yet. Can you provide more info?

**Comment by revansx** [comment]
I believe it is in regards to the actor migration. All I know is that I had errors when I clicked on my "Pending Reviews" in my wikis after I upgraded to 34.x and this was one of the changes I needed to implement to fix it. Does that help?

**Comment by jamesmontalvo3** [comment]
Okay. I haven't used WatchAnalytics yet on a live server running 1.34, only on dev servers. Thanks for the additional info.

**Comment by olsonjaredm** [comment]
Hey guys! I can confirm this error and that this is the correct fix for compatibility with MW 1.34+.
When loading the Pending Reviews page, the extension looks to see if there are any deleted pages to display to the user (`function getDeletionLog`). If there are, it looks for the fields `logging.log_user` and `logging.log_user_text`.

These were not present in our MW 1.35.5 DB table, because they were [removed in MW 1.34] (https://www.mediawiki.org/wiki/Manual:Logging_table#log_user) in favor of `log_actor`.

**Review by olsonjaredm — APPROVED** [review]
Verified fix on 1.35.5.

**Pull request merged**
